export const brandsList = [
        {name: 'almay'},
        {name: 'alva'},
        {name: 'anna sui'},
        {name: 'annabelle'},
        {name: 'benefit'},
        {name: 'boosh'},
        {name: 'burt\'s bees'},
        {name: 'butter london'},
        {name: 'c\'est moi'},
        {name: 'cargo cosmetics'},
        {name: 'china glaze'},
        {name: 'clinique'},
        {name: 'coastal classic creation'},
        {name: 'colourpop'},
        {name: 'covergirl'},
        {name: 'dalish'},
        {name: 'deciem'},
        {name: 'dior'},
        {name: 'dr. hauschka'},
        {name: 'e.l.f.'},
        {name: 'essie'},
        {name: 'fenty'},
        {name: 'glossier'},
        {name: 'green people'},
        {name: 'iman'},
        {name: 'l\'oreal'},
        {name: 'lotus cosmetics usa'},
        {name: 'maia\'s mineral galaxy'},
        {name: 'marcelle'},
        {name: 'marienatie'},
        {name: 'maybelline'},
        {name: 'milani'},
        {name: 'mineral fusion'},
        {name: 'misa'},
        {name: 'mistura'},
        {name: 'moov'},
        {name: 'nudus'},
        {name: 'nyx'},
        {name: 'orly'},
        {name: 'pacifica'},
        {name: 'penny lane organics'},
        {name: 'physicians formula'},
        {name: 'piggy paint'},
        {name: 'pure anada'},
        {name: 'rejuva minerals'},
        {name: 'revlon'},
        {name: 'sally b\'s skin yummies'},
        {name: 'salon perfect'},
        {name: 'sante'},
        {name: 'sinful colours'},
        {name: 'smashbox'},
        {name: 'stila'},
        {name: 'suncoat'},
        {name: 'w3llpeople'},
        {name: 'wet n wild'},
        {name: 'zorah'},
        {name: 'zorah biocosmetiques'}
]